language: ruby

rvm:
   - 1.9.3
   - 2.0.0
   - 2.1.5
   - 2.2.0
   - rbx
   - jruby

matrix:
   allow_failures:
     - rvm: rbx
     - rvm: jruby

before_script:
   - echo "- $GMAIL_USER\n- $GMAIL_PASSWORD" > spec/account.yml
