language: ruby

rvm:
   - 2.1.3

matrix:
   allow_failures:
     - rvm: rbx
     - rvm: jruby

before_script:
   - printf "- $GMAIL_USER\n- $GMAIL_PASSWORD\n" > spec/account.yml
   - cat spec/account.yml
