language: ruby

rvm:
   - 2.1.3

matrix:
   allow_failures:
     - rvm: rbx
     - rvm: jruby

before_script:
   - printf '%s%s\n%s%s\n' '- ' $GMAIL_USER '- ' $GMAIL_PASSWORD > spec/account.yml
   - cat spec/account.yml
